#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <math.h>

#define NODE struct node
#define CONN struct connection
#define NETW struct network
#define DMAT struct distance_matrix
#define SMAT struct similarity_matrix

NODE {
    char *name;
    float x;
    float y;
    float fx;
    float fy;
};

CONN {
    NODE *node1;
    NODE *node2;
    float distance;
};

NETW {
    int num_nodes;
    NODE **nodes;
    CONN **connections;
};

DMAT {
    char **names;
    int num_sets;
    float **distances;
};

SMAT {
    char **names;
    int num_sets;
    float **similarities;
};

// Calculate the Hooke force on the two nodes that is generated by the 
// difference between the actual distance between them and the distance
// between their xy positions. Add that force to fx and fy.
void addHookeForce(CONN *conn) {
    // The total Hooke force scales linearly with the difference between the
    // distance from the distance matrix and the xy difference.

    NODE *a = conn->node1;
    NODE *b = conn->node2;

    float dx = b->x - a->x;
    float dy = b->y - a->y;

    // Pythagoras
    float dist = sqrtf(dx * dx + dy * dy);
    
    // Positive means the nodes want to get farther apart
    float diff = conn->distance - dist;

    float fx = 0.0;
    float fy = 0.0;

    if(dist == 0) {
        // Randomize the vector that gives the xy distance
        dx = (float)(rand() - rand()) / RAND_MAX;
        dy = (float)(rand() - rand()) / RAND_MAX;
        dist = sqrtf(dx * dx + dy * dy);
        // This will still apply the correct amount of force in a random
        // direction.
        fx = dx * diff / dist;
        fy = dy * diff / dist;
    } else {
        // If dx is 0, there is no force along the x axis.
        fx = dx * diff / dist;
        // If dy is 0, there is no force along the y axis.
        fy = dy * diff / dist;
    }

    a->fx -= fx;
    a->fy -= fy;
    b->fx += fx;
    b->fy += fy;

    return;
}

NETW *netwFromDmat(DMAT *dmat) {
    int i = 0, j = 0;
    int num_sets = dmat->num_sets;
    NODE **nodes = calloc(num_sets, sizeof(NODE *));
    for(i = 0; i < num_sets; i++) {
        nodes[i] = calloc(1, sizeof(NODE));
        nodes[i]->name = dmat->names[i];
        nodes[i]->x = (float)rand() / RAND_MAX;
        nodes[i]->y = (float)rand() / RAND_MAX;
        nodes[i]->fx = 0;
        nodes[i]->fy = 0;
    }
    CONN **conns = calloc(num_sets * num_sets, sizeof(CONN *));
    for(i = 0; i < num_sets; i++) {
        for(j = 0; j < num_sets; j++) {
            conns[i * num_sets + j] = calloc(1, sizeof(CONN));
            conns[i * num_sets + j]->node1 = nodes[i];
            conns[i * num_sets + j]->node2 = nodes[j];
            conns[i * num_sets + j]->distance = dmat->distances[i][j];
        }
    }
    NETW *netw = calloc(1, sizeof(NETW));
    netw->num_nodes = dmat->num_sets;
    netw->nodes = nodes;
    netw->connections = conns;
    return netw;
}

void fprint_netw(FILE *fp, NETW* netw) {
    fprintf(fp, "\033[2J");
    fprintf(fp, "+----------+---------+---------+---------+---------+\n");
    fprintf(fp, "|                        NODES                     |\n");
    fprintf(fp, "+----------+---------+---------+---------+---------+\n");
    fprintf(fp, "|NAME      |    X    |    Y    |    Fx   |    Fy   |\n");
    fprintf(fp, "+----------+---------+---------+---------+---------+\n");
    int i = 0;
    for(i = 0; i < netw->num_nodes; i++) {
        NODE *n = netw->nodes[i];
        fprintf(fp, "|%-10s|%9f|%9f|%9f|%9f|\n", n->name, n->x, n->y, n->fx, n->fy);
    }
    fprintf(fp, "+----------+---------+---------+---------+---------+\n\n\n");
    fprintf(fp, "+----------+----------+---------+---------+---------+---------+\n");
    fprintf(fp, "|                          CONNECTIONS                        |\n");
    fprintf(fp, "+----------+----------+---------+---------+---------+---------+\n");
    fprintf(fp, "|   FROM   |    TO    |    DX   |    DY   |   DIST  |   GOAL  |\n");
    fprintf(fp, "+----------+----------+---------+---------+---------+---------+\n");
    for(i = 0; i < netw->num_nodes * netw->num_nodes; i++) {
        NODE *a = netw->connections[i]->node1;
        NODE *b = netw->connections[i]->node2;
        float dx = b->x - a->x;
        float dy = b->y - a->y;
        float dist = sqrtf(dx * dx + dy * dy);
        float goal = netw->connections[i]->distance;
        fprintf(fp, "|%-10s|%-10s|%9f|%9f|%9f|%9f|\n", a->name, b->name, dx, dy, dist, goal);
    }
    fprintf(fp, "+----------+----------+---------+---------+---------+---------+\n\n\n\n\n");

}

void netw_step(NETW* netw) {
    int i = 0;
    for(i = 0; i < netw->num_nodes * netw->num_nodes; i++) {
        addHookeForce(netw->connections[i]);
    }
    for(i = 0; i < netw->num_nodes; i++) {
        netw->nodes[i]->x += netw->nodes[i]->fx / 10;
        netw->nodes[i]->y += netw->nodes[i]->fy / 10;
        netw->nodes[i]->fx = 0;
        netw->nodes[i]->fy = 0;
    }
}

SMAT *readSMATFromFP(FILE *fp) {
    fprintf(stderr, "Reading distance matrix from file handle <%p>.\n", fp);
    
    // Similarity matrix is in the following format:

    //      ; SET_A; SET_B; SET_C; SET_D
    // SET_A: 100.0;  14.7;  21.2;   9.3
    // SET_B:  14.7; 100.0;  16.3;   5.4
    // SET_C:  21.2;  16.3; 100.0;  11.3
    // SET_D:   9.3;   5.4;  11.3; 100.0
    //

    char c = '\0';
    int i = 0, j = 0;
    int num_sets = 0;
    int col_num = 0;
    
    // Count the number of sets.
    while((c = fgetc(fp)) && c != EOF && c != '\n') {
        if(c == ';') {
            num_sets++;
        }
    }

    SMAT *smat = calloc(1, sizeof(SMAT));

    smat->num_sets     = num_sets;
    smat->names        = calloc(num_sets, sizeof(char *));
    smat->similarities = calloc(num_sets, sizeof(float *));
    for(i = 0; i < num_sets; i++) {
        smat->similarities[i] = calloc(num_sets, sizeof(float));
    }

    fprintf(stderr, "There are %i sets.\n", num_sets);
    for(i = 0; i < num_sets; i++) {
        char *set_name = calloc(65536, sizeof(char));
        fscanf(fp, "%[^;]", set_name);
        set_name = realloc(set_name, strlen(set_name) + 1);
        smat->names[i] = set_name;
        (void)fgetc(fp); // Silently remove the colon
        fprintf(stderr, "Set %i is named %s.\n", i, set_name);
        for(j = 0; j < num_sets; j++) {
            float sim = 0.0;
            fscanf(fp, "%f", &sim);
            fprintf(stderr, "similarity[%i][%i] = %f.\n", i, j, sim);
            (void)fgetc(fp); // Silently ignore semicolon
            if(sim <= 0.0) sim = 0.01;
            smat->similarities[i][j] = sim;
        }

    }
    
    return smat;
}

DMAT *dmatFromSMAT(SMAT *smat) {
    DMAT *dmat = calloc(1, sizeof(DMAT));

    dmat->num_sets = smat->num_sets; 
    dmat->names    = smat->names;

    dmat->distances = calloc(smat->num_sets, sizeof(float *));

    int i = 0, j = 0;
    for(i = 0; i < smat->num_sets; i++) {
        dmat->distances[i] = calloc(smat->num_sets, sizeof(float));
    }
    for(i = 0; i < smat->num_sets; i++) {
        for(j = 0; j < smat->num_sets; j++) {
            dmat->distances[i][j] = -logf(smat->similarities[i][j] / 100.0);
        }
    }
    return dmat;
}

int main(void) {
    SMAT *smat = readSMATFromFP(stdin);
    int i = 0, j = 0;
    for(i = 0; i < smat->num_sets; i++) {
        fprintf(stderr, ";%s", smat->names[i]);
    }
    puts("");
    for(i = 0; i < smat->num_sets; i++) {
        fprintf(stderr, "%s", smat->names[i]);
        for(j = 0; j < smat->num_sets; j++) {
            fprintf(stderr, ";%f", smat->similarities[i][j]);
        }
        puts("");
    }
    DMAT *dmat = dmatFromSMAT(smat);
    for(i = 0; i < dmat->num_sets; i++) {
        fprintf(stderr, ";%s", dmat->names[i]);
    }
    puts("");
    for(i = 0; i < dmat->num_sets; i++) {
        fprintf(stderr, "%s", dmat->names[i]);
        for(j = 0; j < dmat->num_sets; j++) {
            fprintf(stderr, ";%f", dmat->distances[i][j]);
        }
        puts("");
    }
    NETW* netw = netwFromDmat(dmat);
    for(i = 0; i < 100; i++) {
        netw_step(netw);
    }
    for(i = 0; i < netw->num_nodes; i++) {
        NODE *n = netw->nodes[i];
        fprintf(stdout, "%s; %f; %f\n", n->name, n->x, n->y);
    }
    for(i = 0; i < dmat->num_sets; i++) {
        fprintf(stderr, ";%s", dmat->names[i]);
    }
    puts("");
    for(i = 0; i < dmat->num_sets; i++) {
        fprintf(stderr, "%s", dmat->names[i]);
        for(j = 0; j < dmat->num_sets; j++) {
            fprintf(stderr, ";%f", dmat->distances[i][j]);
        }
        puts("");
    }
    return EXIT_SUCCESS;
}
